### ISSUE TITLE
efc error

### ISSUE THREAD

**Issue by ghost** [Ugranziol/appRiori#1]
Hello.

When I run

**library(sjPlot)
library(appRiori)
appRiori()** 

the following error appears:

**Listening on http://127.0.0.1:3374
Warning: Error in : 'efc' is not an exported object from 'namespace:sjPlot'**

**Comment by mmrabe** [comment]
Thanks a lot for bringing this to our attention, @armelbrizuela! Generally, you can also use other packages’ datasets as default datasets in appRiori by loading the respective package before calling `appRiori()` like you did. The way we browsed installed datasets was a bit rocky and it seemed to produce an error where the package (`sjPlot`) does not export the data set  (`efc`) as part of its namespace (as `sjPlot::efc`) but only with `data("efc", package="sjPlot")`. This is now fixed as of commit a8763686fec189197e1110f6a3a1467c1e7ddf73 and will work in the next version. You can already download the fixed development package using `remotes::install_github("Ugranziol/appRiori")`.
